xceed-nitj/AMS-with-TimeTable

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/timetableadmin/creatett.jsx
client/src/timetableadmin/timetable.jsx

Reverts xceed-nitj/AMS-with-TimeTable#2

Revert "Pihu2"

---

client/src/timetableadmin/addfaculty.jsx
client/src/timetableadmin/addsemester.jsx

Chakra UI styling in addFaculty and addSemester pages

Updated addfaculty and addsemester with chakra UI

---

client/src/timetableadmin/addfaculty.jsx
client/src/timetableadmin/addsemester.jsx

Reverts xceed-nitj/AMS-with-TimeTable#75

Revert "Revert "Updated addfaculty and addsemester with chakra UI""

---

client/src/getenvironment.js
client/src/timetableadmin/masterdelete.jsx
client/src/timetableadmin/masterfaculty.jsx
client/src/timetableadmin/masterroom.jsx

Reverts xceed-nitj/AMS-with-TimeTable#163

Revert "Favicon updated"

---

server/src/index.js
server/src/models/usermanagement/otp.js
server/src/modules/timetableModule/controllers/addfacultyprofile.js
server/src/modules/timetableModule/controllers/instituteloadprofile.js
server/src/modules/timetableModule/routes/addfaculty.js
server/src/modules/timetableModule/routes/addroom.js
server/src/modules/timetableModule/routes/addsem.js
server/src/modules/timetableModule/routes/commonLoad.js
server/src/modules/timetableModule/routes/faculty.js
server/src/modules/timetableModule/routes/index.js
server/src/modules/timetableModule/routes/instituteLoad.js
server/src/modules/timetableModule/routes/locktimetable.js
server/src/modules/timetableModule/routes/masterroom.js
server/src/modules/timetableModule/routes/mastersem.js
server/src/modules/timetableModule/routes/note.js
server/src/modules/timetableModule/routes/subject.js
server/src/modules/timetableModule/routes/timetable.js
server/src/modules/usermanagement/controllers/dto.js
server/src/modules/usermanagement/controllers/forgotpasswordroute.js
server/src/modules/usermanagement/controllers/mailsender.js
server/src/modules/usermanagement/controllers/privateroute.js
server/src/modules/usermanagement/controllers/resetpasswordroute.js
server/src/modules/usermanagement/controllers/ttadminroute.js
server/src/modules/usermanagement/controllers/user.js
server/src/modules/usermanagement/controllers/usercontroller.js
server/src/modules/usermanagement/routes/routes.js
server/src/modules/usermanagement/routes/user.js

instead of Date.now() it's using timeout to delete after 10 min

Fixed OTP expiring after 30 sec to 10 min , refactored files

---

server/src/modules/usermanagement/controllers/otpbody.ejs
server/src/modules/usermanagement/controllers/resetpasswordroute.js
server/src/modules/usermanagement/otpbody.ejs

in resetpasswordroute changed newPassword-> password

Changed newPassword -> password and updated otp message

---

client/package.json
client/src/timetableadmin/editmasterfaculty.jsx
client/yarn.lock
server/src/modules/timetableModule/routes/faculty.js

Reverts xceed-nitj/AMS-with-TimeTable#273

Revert "Changes made in edit master faculty"

---

client/src/App.jsx
client/src/conferencemodule/Tabs/Accomodation.jsx
client/src/conferencemodule/Tabs/Events.jsx
client/src/conferencemodule/Tabs/Souvenir.jsx
client/src/conferencemodule/Tabs/SponsorshipRates.jsx
client/src/conferencemodule/components/Sidebar.jsx
server/src/index.js

Added new Tabs in conference module adminpanel

Avnash new

---

client/src/App.jsx
client/src/reviewmodule/pages/PrmEditorDashboard.jsx
server/src/modules/reviewModule/controller/reviewer.js
server/src/modules/reviewModule/routes/reviewer.js

Reverts xceed-nitj/AMS-with-TimeTable#370

Revert "Revert "added dummy editor dashboard""

---

client/src/App.jsx
client/src/reviewmodule/pages/UpdateReviewerStatus.jsx
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/routes/event.js

Invitation Mail link will be sent to the Reviewer for Acceptance/Rejection , also frontend page is created for the same .

implemented Invitation mail Link to the reviewer

---

server/src/getEnvironmentURL.js
server/src/modules/reviewModule/controller/event.js

created the GetEnvironment function for different links of localhost production and nitjserver for frontend part .

GetEnvironment function for different links of localhost production and nitjServer.

---

server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/routes/event.js
server/yarn.lock

created a function UpdateTemplates to handle patch request from frontend

made save button for templates working

---

client/src/App.jsx
client/src/quizModule/creator/addQuestion/AddInstruction.jsx
client/src/quizModule/creator/addQuestion/AddQuestion.jsx
client/src/quizModule/creator/addQuestion/AddQuestionHome.jsx
client/src/quizModule/creator/addQuestion/PreviewInstructions.jsx
client/src/quizModule/creator/addQuestion/settings.jsx
client/src/quizModule/creator/createQuiz/CreateQuiz.jsx

Merged remaining faculty routes to frontend in App.jsx
Commented css disturbing Revenue Section in HomePage

Merged faculty routes, css issue in App.jsx

---

client/src/filedownload/downloadpdf.js
client/src/filedownload/downloadsummary.js
client/src/filedownload/makepdf.jsx

Reverts xceed-nitj/AMS-with-TimeTable#460

Revert "checkfine"

---

server/src/modules/reviewModule/controller/event.js

Added the review template in the mail

Sumitworking

---

client/src/App.jsx
client/src/reviewmodule/pages/EditTemplate.jsx
client/src/reviewmodule/pages/PrmEditorDashboard.jsx
server/src/models/reviewModule/event.js
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/routes/event.js

1 .Created a new File EditTemplate for Creating templates and made the corresponding controller function .
2. Updated the path for communication Templates and corrected the mistakes in event.js model .

Corrected the Template Save Problem by making another File

---

server/src/models/reviewModule/event.js
server/src/modules/reviewModule/controller/event.js

1)Added the Signature in Model 
2) Added the signature at the last of reviewer Invitation mail

Added the Signature in Model and at the end of mail send to reviewer

---

client/src/reviewmodule/pages/EditTemplate.jsx
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/routes/event.js

Corrected the UpdateEvent route and added the Template in  resendInvitation mail .

corrected the UpdateEvent route and resendInvitation mail

---

client/src/reviewmodule/pages/EditTemplate.jsx

Used Tab components from ChakraUI to implement tabs.

Added tabs to EditTemplate.jsx

---

client/src/reviewmodule/pages/AddReviewer.jsx
client/src/reviewmodule/pages/addeditor.jsx
client/src/reviewmodule/pages/eventregistration.jsx
server/src/models/reviewModule/event.js
server/src/models/usermanagement/user.js
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/controller/papers.js
server/src/modules/usermanagement/controllers/usercontroller.js

Reverts xceed-nitj/AMS-with-TimeTable#495

Revert " merged the users and prm-users collection"

---

client/src/reviewmodule/pages/AddReviewer.jsx
client/src/reviewmodule/pages/addeditor.jsx
client/src/reviewmodule/pages/eventregistration.jsx
server/src/models/reviewModule/event.js
server/src/models/usermanagement/user.js
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/controller/papers.js
server/src/modules/usermanagement/controllers/usercontroller.js

Reverts xceed-nitj/AMS-with-TimeTable#496

Revert "Revert " merged the users and prm-users collection""

---

client/src/reviewmodule/pages/PrmEditorDashboard.jsx
client/yarn.lock
server/package-lock.json
server/package.json
server/yarn.lock

Reverts xceed-nitj/AMS-with-TimeTable#508

Revert "issue resolved Editor dashboard improvements #502"

---

client/src/reviewmodule/pages/UpdateReviewerStatus.jsx

Redirect  the reviewer to the reviewer login page after reject/accept button.

Redirect after reject/accept button for the reviewer

---

client/src/reviewmodule/pages/editorevent.jsx

styling changed

---

client/src/reviewmodule/pages/editorevent.jsx

mobile styling done

---

client/src/reviewmodule/pages/AddReviewer.jsx

styles updated

---

client/src/reviewmodule/pages/EditTemplate.jsx

-> Tab overflow added
-> fixed glitch where _id keeps showing as a tab

Responsiveness added to EditTemplate.jsx

---

client/src/reviewmodule/pages/addTracks.jsx

popup added

---

client/src/reviewmodule/pages/allpapers.jsx
server/src/modules/reviewModule/controller/papers.js

the format of email is
You have been added as a reviewer to the paper with title: <paper.title>
<event.templates.paperAssignment>
Please click [here](viewlink) to view the papers
<signature>

added a feature to send email to reviewers on assigning a paper

---

client/src/App.jsx
client/src/reviewmodule/pages/ReviewQuestion.css
client/src/reviewmodule/pages/ReviewQuestion.jsx
client/src/reviewmodule/pages/ReviewQuestionHome.jsx
server/src/modules/reviewModule/controller/reviewQuestion.js
server/src/modules/reviewModule/routes/reviewQuestion.js

Created a frontend page for saving questions .

Created Frontend Page that save ReviewQuestion to the DB. #530

---

client/src/quizModule/creator/addQuestion/settings.css

I have improvised the designing of the Settings page.

QZ: Faculty Quiz Instruction and Settings Design(#556)

---

client/src/reviewmodule/components/NavBar.jsx

navbar updated

---

client/src/reviewmodule/pages/ReviewQuestion.css
client/src/reviewmodule/pages/ReviewQuestion.jsx

Functionality to add type of question and option are available if single correct or multiple correct is choosen

In ReviewQuestion editor can add type and options also

---

client/src/reviewmodule/pages/Main.jsx
client/src/reviewmodule/pages/searchEvent.jsx

-> Search bar added
-> Pagination added
-> Added field in table to view Deadline
-> Responsiveness added

Search and Pagination added to searchEvent.jsx

---

client/src/App.jsx
client/src/reviewmodule/pages/Review.jsx
client/src/reviewmodule/pages/ReviewQuestion.jsx
server/src/models/reviewModule/reviewQuestion.js
server/src/modules/reviewModule/controller/papers.js
server/src/modules/reviewModule/controller/reviewQuestion.js
server/src/modules/reviewModule/controller/user.js
server/src/modules/reviewModule/routes/paper.js
server/src/modules/reviewModule/routes/reviewQuestion.js
server/src/modules/reviewModule/routes/user.js

Regarding issue #566  
To access the page you need to have eventId , paperId , reviewerId then only it can be open . 
Made the controller functions  and routes  .

made the frontend page for saving the answers of reviewQuestion

---

client/src/App.jsx
client/src/reviewmodule/pages/ReviewQuestion.jsx
server/src/models/reviewModule/reviewQuestion.js
server/src/modules/reviewModule/controller/reviewQuestion.js

To access the ReviewQuestion Page this is the path -:
<Route path="/prm/:eventId/ReviewQuestion" element={<ReviewerQuestion/>}/>

Removed the paperId field from reviewQuestion

---

client/src/reviewmodule/pages/Review.jsx
client/src/reviewmodule/pages/pendingAssignment.jsx
server/src/models/reviewModule/review.js
server/src/modules/reviewModule/controller/reviewQuestion.js
server/src/modules/reviewModule/routes/reviewQuestion.js

Fixes #566 
To access the frontend page you need to login then go the the pending assignment table then click on the answer corresponding to the paper , it will redirect you to the frontend page.

Review answer is liked to pending assignment table of reviewer tab .

---

client/src/reviewmodule/components/PaperDetails.jsx
client/src/reviewmodule/components/SelectTracks.jsx

added track field in new submission steps

---

client/src/reviewmodule/pages/ReviewQuestion.css
client/src/reviewmodule/pages/ReviewQuestion.jsx

-> Continued Website design language by using common elements 
-> chakra UI elements used
-> Save button dynamically appears when needed

Updated ReviewQuestion.js

---

client/src/reviewmodule/components/AuthorDetails.jsx
client/src/reviewmodule/components/AuthorForm.jsx
client/src/reviewmodule/components/Submission.jsx
client/src/reviewmodule/pages/MultiStepForm.jsx
client/src/reviewmodule/pages/allpapers.jsx
client/src/reviewmodule/state/atoms/paperState.js
server/src/models/reviewModule/paper.js
server/src/modules/reviewModule/controller/reviewer.js
server/src/modules/reviewModule/controller/uploadFileMiddleWare.js
server/src/modules/reviewModule/routes/reviewer.js

1)fixed the issue where the authors were not showing up in frontend
2)added an option in allpapers for the editor to assign due dates to reviewers

author details fixed and due date added

---

client/src/reviewmodule/pages/ReviewQuestionHome.jsx

Review question

---

client/src/reviewmodule/pages/PrmEditorDashboard.jsx

review questions button added

---

client/src/reviewmodule/components/NavBar.jsx

issue #527 solved 

---

server/src/models/reviewModule/defaultQuestion.js
server/src/modules/reviewModule/controller/defaultQuestion.js
server/src/modules/reviewModule/routes/defaultQuestion.js

Now i have just created a Schema routes and controller . Supedadmin route is not added yet

created schema controller routes #567 for default questions

---

client/src/certificatemodule/pages/SelectCertficate.jsx
client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/certificatetemplates/basic01.jsx
client/src/certificatemodule/pages/participantCerti.jsx
server/src/modules/certificateModule/controllers/certificate.js

Reverts xceed-nitj/AMS-with-TimeTable#617

Revert "Feature/title money goyal"

---

client/src/reviewmodule/pages/Review.jsx
server/src/models/reviewModule/review.js
server/src/modules/reviewModule/controller/review.js
server/src/modules/reviewModule/routes/index.js
server/src/modules/reviewModule/routes/review.js

review get disabled when review gets submitted.

#566 disabled when review gets submitted

---

server/src/modules/reviewModule/controller/papers.js
server/src/modules/reviewModule/routes/paper.js

added a route to fetch papers based on authorid

 issue #597 

---

client/src/reviewmodule/pages/ReviewQuestion.jsx
server/src/models/reviewModule/reviewQuestion.js
server/src/modules/reviewModule/controller/reviewQuestion.js

Made changes in Schema 
made changes in addreviewQuestion Controller 
Made changes in reviewQuestion.jsx

completed #613 added the order field

---

server/src/models/reviewModule/defaultQuestion.js
server/src/models/reviewModule/event.js
server/src/models/reviewModule/paper.js
server/src/models/reviewModule/review.js
server/src/models/reviewModule/reviewQuestion.js
server/src/modules/reviewModule/controller/event.js

1)added a feature where if the user is not allocated the "PRM" role they will be alloted the role \
2)added timestamps in all the required schema

issue #631 #624 user role allocation and timestamps in schema

---

client/src/reviewmodule/pages/Review.jsx
client/src/reviewmodule/pages/pendingAssignment.jsx
server/src/models/reviewModule/review.js
server/src/modules/reviewModule/controller/reviewQuestion.js

PaperId is changed from string to ObjectId 
order field is added in review schema 
in review.jsx questions are arranged according to the order 
order field is now also saved in review db .

#625 paperId is changed to objectId and review have order field

---

client/src/reviewmodule/components/PRMSidebar.jsx
client/src/reviewmodule/pages/SubmittedPapers.jsx

-> Users can now view papers submitted by them in a searchable, paginated format 
-> Link to paper summary added

(ISSUE #587)Submitted Papers page added

---

client/src/reviewmodule/pages/ReviewQuestion.jsx
client/src/reviewmodule/pages/ReviewQuestionHome.jsx
server/src/modules/reviewModule/controller/reviewQuestion.js

-> Edit and Delete button added.
-> modified ReviewQuestion.jsx to add patch functionality -> sort functionality added to ReviewQuestionHome.jsx -> minor changes to reviewQuestion.js (backend)

(Issue #614) Edit and Delete added to ReviewQuestionHome.jsx

---

client/src/reviewmodule/components/PaperDetails.jsx
client/src/reviewmodule/components/SelectTracks.jsx

fixed the selectTracks.jsx file where no handlechange function was available

issue #635

---

server/src/modules/reviewModule/controller/review.js
server/src/modules/reviewModule/routes/review.js

created routes to find answer using eventId and paperId . You will get answer array through that you can access each and every answer

#645 created routes to find answer using eventId and paperId

---

server/src/modules/reviewModule/controller/review.js
server/src/modules/reviewModule/routes/review.js

Reverts xceed-nitj/AMS-with-TimeTable#650

Revert "#645 created routes to find answer using eventId and paperId"

---

server/src/models/reviewModule/defaultQuestion.js
server/src/modules/reviewModule/controller/defaultQuestion.js
server/src/modules/reviewModule/controller/review.js

corrected the controller function

corrected the controller function

---

server/src/modules/reviewModule/controller/papers.js

resolved creating duplicate author while submitting paper

issue #605

---

client/src/reviewmodule/pages/Review.jsx

-> Now submitted reviews are shown on the page and new reviews are prevented -> Page design improved
-> Submitted time shown

( ISSUE #623 ) updated Review.jsx

---

client/src/reviewmodule/pages/ReviewQuestionHome.jsx

-> compare function added to sort().

( ISSUE #637 )  bug fix in sorting (ReviewQuestionHome.jsx)

---

client/src/App.jsx
client/src/reviewmodule/pages/DefaultQuestion.jsx

Created frontend page to add default question #646
Copied the ReviewQuestion Page code and changed the path for post request .

Created frontend page to add default question #646

---

client/src/reviewmodule/components/AuthorForm.jsx
server/src/modules/reviewModule/controller/papers.js

added papersubmission template to the mail sent on adding new author

fixed the new author email issue

---

client/src/reviewmodule/pages/EditTemplate.jsx

-> Fixed the issue in which the different Editors were not of the same height 
-> Changed header to black theme

( ISSUE #640 )  Fixes in EditTemplate.jsx

---

client/src/App.jsx
client/src/reviewmodule/pages/DefaultQuestion.jsx
client/src/reviewmodule/pages/DefaultQuestionHome.jsx
server/src/modules/reviewModule/routes/defaultQuestion.js

Created a frontend page for showing DefaultQuestion. 
It has Edit , Delete Option 
Enhanced the Sort Function so that questions with same order can also be shown .
path for showing Question is -: /prm/DefaultQuestionHome 
and for adding Question is -:  /prm/DefaultQuestion

#665 Created a frontend page for showing DefaultQuestion

---

client/src/reviewmodule/components/NavBar.jsx

login redirection removed from some urls

issue #663 solved (not redirecting to /login)

---

client/src/App.jsx
client/src/reviewmodule/pages/PaperSummary.jsx
server/src/modules/reviewModule/controller/review.js

-> users can view their Paper's submitted info, status and feedback by all the reviewers
-> Fetching of author names is PENDING
-> Attachment buttons do not work as of now

( ISSUE #599 )  Added PaperSummary.jsx page

---

server/src/models/reviewModule/paper.js
server/src/modules/reviewModule/controller/uploadFile.js

Changed the paperId to number and assigned it according to paper submission count

Issue #661

---

server/src/models/reviewModule/event.js
server/src/models/reviewModule/review.js
server/src/models/reviewModule/reviewQuestion.js
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/controller/reviewQuestion.js

Done the necessary changes in addevent controller.

#647 default question will be added to reviewQuestion when an event is created 

---

client/src/reviewmodule/components/NavBar.jsx
client/src/reviewmodule/pages/editorevent.jsx

date problem fixed #698

---

server/src/models/reviewModule/event.js
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/routes/event.js

Created startSubmission field and route to update it

#706 Created startSubmission field

---

client/src/reviewmodule/pages/editorevent.jsx
client/src/reviewmodule/pages/userRegistration.jsx
server/src/modules/reviewModule/controller/uploadFile.js

Merged user registration page
Added time for deadline in conference page
Update paper submission check with time too

Issue #562, #702

---

client/src/quizModule/components/quill/viewer.css
client/src/quizModule/creator/addQuestion/AddQuestion.css
client/src/quizModule/creator/addQuestion/AddQuestion.jsx
client/src/quizModule/creator/addQuestion/AddQuestionHome.css
client/src/quizModule/creator/addQuestion/AddQuestionHome.jsx
client/yarn.lock

Reverts xceed-nitj/AMS-with-TimeTable#607

Revert "QZ: faculty quiz add question home design (#555)"

---

client/src/quizModule/components/quill/viewer.css
client/src/quizModule/creator/addQuestion/AddQuestion.css
client/src/quizModule/creator/addQuestion/AddQuestion.jsx
client/src/quizModule/creator/addQuestion/AddQuestionHome.css
client/src/quizModule/creator/addQuestion/AddQuestionHome.jsx
client/yarn.lock

Reverts xceed-nitj/AMS-with-TimeTable#723

Revert "Revert "QZ: faculty quiz add question home design (#555)""

---

server/src/models/reviewModule/user.js

-> restored user.js due to existing dependencies

Temporarily restored user.js

---

client/src/reviewmodule/pages/AddReviewer.jsx
client/src/reviewmodule/pages/addTracks.jsx

-> Edited addtracks.jsx and AddReviewer.jsx

( ISSUE #583 )  added differentiation between Loading and no data found

---

server/src/models/reviewModule/event.js
server/src/modules/reviewModule/controller/papers.js

added reviewtime as the due date for reviewers assigned to papers

issue #642

---

client/src/reviewmodule/pages/PrmEditorDashboard.jsx
client/src/reviewmodule/pages/StartSubmission.jsx

->  conf details, add tracks, review questions button moved to Start Submission page. (removed from editor dashboard). -> Other buttons disabled till startSubmission value in Database set to true

( ISSUE #710 )  Removed and Disabled buttons in editor dashboard

---

client/package.json
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/controller/papers.js
server/src/modules/reviewModule/controller/reviewer.js

All other files will use usermanagement user.js file instead of reviewModule user.js file

#728 Removed the use of review user.js file in review Module

---

client/package.json
client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/certificatetemplates/akleem/Content.jsx
client/src/certificatemodule/pages/certificatetemplates/basic01.jsx
client/yarn.lock
server/src/models/certificateModule/certificate.js

- parent element of logo has been given height and width variables to achieve variable size and conserve aspect ratio of image

changed logo size as variable

---

client/src/reviewmodule/components/PRMSidebar.jsx

icon changed #712

---

client/src/reviewmodule/components/AuthorDetails.jsx
client/src/reviewmodule/components/AuthorForm.jsx
client/src/reviewmodule/components/Submission.jsx
server/src/modules/reviewModule/controller/papers.js
server/src/modules/reviewModule/controller/uploadFile.js
server/src/modules/reviewModule/controller/uploadFileMiddleWare.js
server/src/modules/reviewModule/routes/paper.js

1)added the new usercreation and existing user validation at the last step of paper submission 
2)fixed the issue where 2 mails were being sent to new users during paper submission 
3)sending the current logged in user from frontend rather than using the middleware

issue #630

---

client/src/reviewmodule/pages/Invitations.jsx
client/src/reviewmodule/pages/editorevent.jsx

Made button visible for Invited status in invitation tab
resolved the error in add conference tab

Issue #751 #753

---

client/src/reviewmodule/pages/searchEvent.jsx

-> added 'Submission not yet started message' to search event page. -> added spinner when page loading
-> centered table headings

( ISSUE #707 )  updated searchEvent.jsx

---

client/src/certificatemodule/pages/SelectCertficate.jsx
client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/certificatetemplates/basic08.jsx
client/src/certificatemodule/pages/certificatetemplates/basic09.jsx
client/src/certificatemodule/pages/certificatetemplates/premium02.jsx
client/src/certificatemodule/pages/certificatetemplates/premium03.jsx
client/src/certificatemodule/pages/certificatetemplates/premium04.jsx

- basic 8,9 and premium 2,3,4 are  also functioning now
- fixed some bugs for initial size of images on adding new element

updated templates - basic 8,9 and premium 2,3,4

---

client/src/reviewmodule/pages/StartSubmission.jsx

-> Bug fixed that shows status as completed even when no tracks were saved -> Bug fix when start submission button was active when 1 or more steps were pending

( ISSUE #750 )  Bug fix in start-submission page

---

client/src/reviewmodule/pages/allpapers.jsx
server/src/models/reviewModule/event.js
server/src/models/reviewModule/paper.js
server/src/models/reviewModule/reviewQuestion.js
server/src/modules/reviewModule/controller/papers.js
server/src/modules/reviewModule/routes/paper.js

Mail will only be sent to the Author if author is linked with the paper . 
after You press make decision it will take time to appear for toast . 
on paper detail page come to the last paper and add the comment and then click make decision then it will work correctly becuase many paper does not have author linked with it .

#720 2 columns added for editor decision

---

client/src/reviewmodule/pages/addTracks.jsx

duplicate track can't be added #752

---

client/src/reviewmodule/pages/PrmEditorDashboard.jsx

Default state of editor dashboard buttons set to true

( ISSUE #755 )  Update PrmEditorDashboard.jsx

---

client/src/App.jsx
client/src/reviewmodule/pages/EditDefaultTemplate.jsx
server/src/models/reviewModule/defaultTemplate.js
server/src/modules/reviewModule/controller/defaultTemplate.js
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/routes/defaultTemplate.js
server/src/modules/reviewModule/routes/event.js
server/src/modules/reviewModule/routes/index.js

Frontend do patch request whenever someone saves the default Templates .
whenever a new event is created default template is automatically put into edit template .

#768 frontend and backend for default communication template

---

client/src/reviewmodule/pages/eventregistration.jsx

Added the buttons that navigate to /prm/DefaultQuestionHome and /prm/editdefaulttemplate

#721 added the buttons

---

client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/signaturemodal.jsx
client/yarn.lock
server/src/modules/certificateModule/controllers/signimagesofuser.js
server/src/modules/certificateModule/routes/certificate.js

- used react-modal to provide upload options for signature images in frontend
- added route to fetch all uploaded images by user
- added controller for the above mentioned

added the option to select signature image from previously uploaded signature images

---

client/src/reviewmodule/pages/allpapers.jsx

-> Now table re-renders whenever any reviewer is removed or added. -> Table variant changed to striped.
-> Table layout refined.
-> Added button to open Reviewer profile page

( ISSUE #784 )  Changes to Paper Details Table

---

client/src/certificatemodule/pages/certificatetemplates/basic01.jsx

- updated src of logo and signature images to get the preview of uploaded images

updated basic01

---

client/package.json
client/src/reviewmodule/pages/Review.jsx
client/yarn.lock

In the PDF following things will be present;
Event name:
paper title:
paper id:
Reviewer Name:
Review questions along with the answer
Author comments
Editor comments
submitted time. 
There is some issue to get Reviewer Name that i will correct

#757 Reviewer Can now download the review

---

client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/certificatetemplates/akleem/index.jsx
server/.gitignore
server/package.json
server/puppeteer.config.cjs
server/src/modules/certificateModule/controllers/convertCertificate.js
server/src/modules/certificateModule/controllers/formDataToObject.js
server/src/modules/certificateModule/routes/certificate.js
server/yarn.lock

- used puppeteer for svg to png conversion
- used pdf-lib for png to pdf conversion 
- updated formdata to object conversion

download certificate updated and some bugs in saving certificate data resolved

---

client/src/reviewmodule/pages/Review.jsx
server/package.json
server/src/modules/reviewModule/controller/review.js

Review pdf attached with the mail will go to the reviewer mail

#790 mail with attachment will go to the reviewer

---

client/src/App.jsx
client/src/certificatemodule/pages/addEvent.jsx
client/src/certificatemodule/pages/cmdashboard.jsx
client/yarn.lock
server/package.json
server/src/modules/certificateModule/controllers/addevent.js
server/src/modules/certificateModule/routes/addevent.js
server/yarn.lock

Provide add event option to each user #797

---

client/src/dashboard/superadmin.jsx
client/src/dashboard/userManagement.jsx

Add user as well in user management 

---

client/src/reviewmodule/pages/SubmittedPapers.jsx
client/src/reviewmodule/pages/userRegistration.jsx
server/src/modules/reviewModule/controller/papers.js
server/src/modules/usermanagement/controllers/usercontroller.js

user registration notification updated
submitted paper filtered according to the user  if he is author or not

Issue #815 #816

---

server/src/modules/reviewModule/controller/review.js

Paperid field of paper will be shown in pdf . 
Alignment is corrected to show the long title or event Names .

#802 #803 solved both issues

---

client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/certificatetemplates/akleem/Content.jsx
client/src/certificatemodule/pages/signaturemodal.jsx
client/src/index.css
client/yarn.lock
server/src/modules/certificateModule/controllers/signimagesofuser.js

- added background remove button in edit section of sign images 
- added 30  more font styles
- fetch only unique signatures by url

added background remove option and some font styles and updated to fetch only unique signatures 

---

client/src/reviewmodule/pages/allpapers.jsx

-> Added search functionality for papers and reviewers 
-> Comments link only shows after completion
->  Delete reviewers option only shows till completion 
-> Author names being shown after fetching
-> added textwrap to title colum,n

( ISSUE #804 -> #809  ) Update allpapers.jsx

---

client/src/reviewmodule/pages/Review.jsx
server/src/models/reviewModule/forms.js
server/src/modules/reviewModule/controller/forms.js
server/src/modules/reviewModule/routes/forms.js
server/src/modules/reviewModule/routes/index.js

Pdf from Download Pdf button in review.jsx will give proper pdf with proper width and multiple pages pdf can be generated .
Forms schema ,routes and controllers are also created

#802 download pdf button will give proper pdf

---

client/src/reviewmodule/pages/allpapers.jsx
server/package.json
server/src/modules/reviewModule/controller/papers.js
server/src/modules/reviewModule/routes/paper.js
server/yarn.lock

Can now download all papers details in form of spreadsheets

Issue #828 

---

client/src/App.jsx
client/src/reviewmodule/pages/Forms.jsx

Frontend page created similar to reviewQuestion it add questions to form.js schema

#798 Created Frontend to submit forms

---

client/src/timetableadmin/viewtt.jsx

-> Updated colors and fixed formatting

( ISSUE #837 )  Update viewtt.jsx

---

client/src/reviewmodule/components/Submission.jsx
client/src/reviewmodule/pages/MultiStepForm.jsx
client/src/reviewmodule/pages/ReviewQuestion.jsx
client/yarn.lock
server/package-lock.json
server/package.json
server/yarn.lock

Reverts xceed-nitj/AMS-with-TimeTable#844

Revert "Pr of Question page"

---

client/src/reviewmodule/components/Submission.jsx
client/src/reviewmodule/pages/MultiStepForm.jsx
client/src/reviewmodule/pages/ReviewQuestion.jsx
client/yarn.lock
server/package-lock.json
server/package.json
server/yarn.lock

Reverts xceed-nitj/AMS-with-TimeTable#847

Revert "Revert "Pr of Question page""

---

client/src/reviewmodule/components/Submission.jsx

-> Fixed issue regarding merging

( ISSUE #837 )  Update Submission.jsx

---

client/src/reviewmodule/pages/UserDetails.jsx
client/src/reviewmodule/pages/userRegistration.jsx
server/src/models/platform.js
server/src/models/usermanagement/user.js
server/src/platform/controller.js
server/src/platform/routes.js
server/src/routes.js

created platform schema and required routes and controllers
add researchArea field in userSchema and modified the frontend accordingly

Issue #832 #836

---

client/src/timetableadmin/mastersearch.jsx
client/src/timetableadmin/ttsummary.jsx
client/src/timetableadmin/viewtt.jsx

-> Added 8 more colors
-> Color coding applied in TT Summary

( ISSUE #837 )  Added subject color coding to TTSummary

---

client/src/reviewmodule/pages/pendingAssignment.jsx
client/src/reviewmodule/pages/reviewsCompleted.jsx

second title removed #811

---

client/src/timetableadmin/mastersearch.jsx
client/src/timetableadmin/ttsummary.jsx
client/src/timetableadmin/viewtt.jsx

-> Added 8 more colors
-> scrapped color mech in TTSummary

( ISSUE #837 )  Removed color mech from TTSummary

---

client/src/certificatemodule/pages/participantdataupload.jsx

- dropdown is added in place of text input
- Name E-mail and Certificate type are made required fields

Issue #714 dropdown for certificate type added and name, mail and certificate type are made required

---

client/src/reviewmodule/components/NavBar.jsx
client/src/reviewmodule/pages/userRegistration.jsx

user page styling done #813

---

client/src/certificatemodule/pages/certificatetemplates/basic02.jsx
client/src/certificatemodule/pages/certificatetemplates/basic03.jsx
client/src/certificatemodule/pages/certificatetemplates/basic04.jsx
client/src/certificatemodule/pages/certificatetemplates/basic05.jsx
client/src/certificatemodule/pages/certificatetemplates/basic06.jsx
client/src/certificatemodule/pages/certificatetemplates/basic07.jsx
client/src/certificatemodule/pages/certificatetemplates/basic08.jsx
client/src/certificatemodule/pages/certificatetemplates/basic09.jsx
client/src/certificatemodule/pages/certificatetemplates/basic10.jsx
client/src/certificatemodule/pages/certificatetemplates/basic11.jsx
client/src/certificatemodule/pages/certificatetemplates/basic12.jsx
client/src/certificatemodule/pages/certificatetemplates/basic13.jsx
client/src/certificatemodule/pages/certificatetemplates/basic14.jsx
client/src/certificatemodule/pages/certificatetemplates/basic15.jsx
client/src/certificatemodule/pages/certificatetemplates/basic16.jsx
client/src/certificatemodule/pages/certificatetemplates/premium01.jsx
client/src/certificatemodule/pages/certificatetemplates/premium02.jsx
client/src/certificatemodule/pages/certificatetemplates/premium03.jsx
client/src/certificatemodule/pages/certificatetemplates/premium05.jsx
client/src/certificatemodule/pages/certificatetemplates/premium06.jsx
client/src/certificatemodule/pages/certificatetemplates/premium07.jsx
server/src/modules/certificateModule/controllers/convertCertificate.js

- All templates are working now

updated certificate templates 

---

client/src/reviewmodule/pages/EditTemplate.jsx
client/yarn.lock
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/controller/uploadFile.js
server/src/modules/reviewModule/routes/event.js
server/yarn.lock

fetched data from the database in communication template, added variables in the mail sent on submitting new papers

---

server/src/modules/certificateModule/routes/addevent.js
server/src/modules/certificateModule/routes/certificate.js
server/src/modules/certificateModule/routes/emails.js
server/src/modules/certificateModule/routes/participant.js
server/src/modules/checkRole.middleware.js
server/src/modules/quizModule/faculty/routes/index.js
server/src/modules/quizModule/faculty/routes/quiz.js

Checking whether the particular event is assigned to the user #841

---

client/src/reviewmodule/pages/Forms.jsx

path to create form is prm/:eventId/:paperIf/forms

frontend to add the forms updated

---

client/src/certificatemodule/pages/cmdashboard.jsx
server/src/modules/certificateModule/routes/certificate.js
server/src/modules/certificateModule/routes/emails.js
server/src/modules/certificateModule/routes/participant.js
server/src/modules/checkRole.middleware.js
server/src/modules/quizModule/faculty/routes/index.js
server/src/modules/quizModule/faculty/routes/quiz.js
server/src/modules/usermanagement/routes/user.js

Reverts xceed-nitj/AMS-with-TimeTable#871

Revert "refactor checkRole middleware and enable add Event button when user has no events"

---

client/src/certificatemodule/pages/cmdashboard.jsx
server/src/modules/certificateModule/routes/addevent.js
server/src/modules/certificateModule/routes/certificate.js
server/src/modules/certificateModule/routes/emails.js
server/src/modules/certificateModule/routes/participant.js
server/src/modules/checkRole.middleware.js
server/src/modules/usermanagement/routes/user.js

Checking whether the particular event is assigned to the user  #841

 enable the "Add New Event" button when the user has no events

---

client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/signaturemodal.jsx

- fixed signature section UI issues
- added copy icon to copy link of previously uploaded signatures
- added toast for failed submission of form

issue #865 issue #878 added copy icon in uploaded page and fixed signature section issues

---

client/src/dashboard/register.jsx

chore: Refactor registration form input handling and validation #877

---

client/src/App.jsx
client/src/reviewmodule/pages/OTPverification.jsx
client/yarn.lock

Reverts xceed-nitj/AMS-with-TimeTable#893

Revert "Improve OTP page #814"

---

client/src/App.jsx
client/src/reviewmodule/pages/FormAnswers.jsx
client/src/reviewmodule/pages/Forms.jsx
server/src/models/reviewModule/formAnswers.js
server/src/models/reviewModule/forms.js
server/src/modules/reviewModule/controller/formAnswers.js
server/src/modules/reviewModule/controller/forms.js
server/src/modules/reviewModule/routes/formAnwers.js
server/src/modules/reviewModule/routes/forms.js
server/src/modules/reviewModule/routes/index.js

path for both pages -: 
<Route path="/prm/:eventId/Forms" element={<Forms/>}/>
<Route path="/prm/:eventId/:formId/:userId/FormAnswers" element={<FormAnswers/>}/>
Forms are now linked with only eventId meanwhile the formanswers are linked with eventId,formId and the user who is submiting the answer

Form and Formanswers frontend and backend code 

---

client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/certificatetemplates/akleem/Content.jsx
client/src/certificatemodule/pages/signaturemodal.jsx

Reverts xceed-nitj/AMS-with-TimeTable#904

Revert "issue #902 edit certificate improvements "

---

client/src/reviewmodule/pages/PaperSummary.jsx

-> Added links to view Code and view Paper in Paper Summary page

( ISSUE #869 )  Added Code and Paper links to PaperSummary

---

client/src/reviewmodule/components/Submission.jsx
client/src/reviewmodule/pages/EditTemplate.jsx
server/src/modules/reviewModule/controller/uploadFile.js

[fetched event fields in communication templates]
[fixed some minor issues in submission]

minor updates

---

client/src/reviewmodule/pages/PaperSummary.jsx
client/src/reviewmodule/pages/SubmittedPapers.jsx
client/src/reviewmodule/pages/searchEvent.jsx

-> Removed Reviewer Comments from paper summary
-> changed page layout
-> pagenation bug fixes in searchEvent & SubmittedPapers

( ISSUE #896 )  Updated Paper Summary

---

client/src/reviewmodule/components/Submission.jsx
client/src/reviewmodule/pages/MultiStepForm.jsx
client/src/reviewmodule/pages/SubmittedPapers.jsx
client/src/reviewmodule/state/atoms/paperState.js
server/src/models/reviewModule/paper.js
server/src/modules/reviewModule/controller/uploadFile.js
server/src/modules/reviewModule/controller/uploadFileMiddleWare.js
server/src/modules/reviewModule/routes/upload.js

[issue]#872
[ added mailing to reviewers on modification]
[changed the uploads folder to common upload folder]

issue #872

---

client/src/reviewmodule/pages/Forms.jsx
server/src/models/reviewModule/forms.js
server/src/modules/reviewModule/controller/forms.js
server/src/modules/reviewModule/routes/forms.js

Currently in db shareWith and deadline could be saved  when clicking save button in form

#880 shareWith and deadline field added

---

client/src/App.jsx
client/src/components/login/LoginForm.jsx
client/src/reviewmodule/pages/AllForms.jsx
client/src/reviewmodule/pages/PrmEditorDashboard.jsx
server/src/modules/reviewModule/controller/event.js
server/src/modules/reviewModule/routes/event.js
server/src/modules/usermanagement/controllers/usercontroller.js
server/src/modules/usermanagement/routes/routes.js

Added Form in editor dashboard
Also made some changes for mailing OTP for email verification

Issue #919

---

client/src/dashboard/superadmin.jsx
client/src/platform/Form.jsx

added a textbox to add values to roles and all other values
added platform page to logs in superadmin page

Platform Form changes

---

client/package.json
client/src/timetableadmin/viewmasterclasstable.jsx
client/yarn.lock

-> hiding columns
-> removal of duplicacy
-> data can be downloaded to CSV

updated /masterdata

---

client/src/filedownload/downloadmergedpdf.js
client/src/filedownload/downloadpdf.js
client/src/filedownload/makepdf.jsx

- created  a new table after 18 rows

added page break in the summary table after 18 rows

---

client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/certificatetemplates/akleem/Content.jsx
client/src/certificatemodule/pages/certificatetemplates/akleem/index.jsx
client/src/certificatemodule/pages/participantdataupload.jsx
server/src/modules/certificateModule/controllers/formDataToObject.js
server/src/modules/certificateModule/helper/multer.middleware.js

- used html2canvas to convert certificate to image

fixed individual certificate download problem

---

client/src/timetableadmin/masterfaculty.jsx

-> users can now download CSV from masterfaculty

( ISSUE #978 )  MasterFaculty download button

---

client/src/components/home/Services/ServiceCard.jsx
client/src/platform/Form.jsx
server/src/models/platform.js
server/src/modules/platform/controller.js
server/src/modules/platform/routes.js

Reverts xceed-nitj/AMS-with-TimeTable#988

Revert "made api's for service and student section on platform page"

---

client/src/components/home/Hero.jsx
client/src/components/home/Navbar.jsx
client/src/timetableadmin/mastersearch.jsx

- removed login required for "/tt/ccommonslots"
- added timetable module link on xceed homepage

Search Meet Slots

---

server/src/models/diabeticsModule/hospital.js
server/src/modules/diabeticsModule/controllers/hospital.js
server/yarn.lock

Start work on models, controllers

feat: add diabeticsModule

---

client/yarn.lock
server/.gitignore
server/package-lock.json
server/package.json
server/src/models/diabeticsModule/dailyDosage.js
server/src/models/diabeticsModule/gamification.js
server/src/models/diabeticsModule/patient.js
server/src/models/diabeticsModule/sickday.js
server/src/modules/diabeticsModule/controllers/dailyDosage.js
server/src/modules/diabeticsModule/controllers/gamification.js
server/src/modules/diabeticsModule/controllers/hospital.js
server/src/modules/diabeticsModule/controllers/patient.js
server/src/modules/diabeticsModule/controllers/sickday.js
server/src/modules/diabeticsModule/routes/dailyDosage.js
server/src/modules/diabeticsModule/routes/gamification.js
server/src/modules/diabeticsModule/routes/hospital.js
server/src/modules/diabeticsModule/routes/index.js
server/src/modules/diabeticsModule/routes/patient.js
server/src/modules/diabeticsModule/routes/sickday.js
server/src/routes.js
server/yarn.lock

Add models, controllers, routes
for
dosage, gamification, hospital, patient, sickday

Controllers

---

client/src/certificatemodule/pages/certificatedesign.jsx
client/src/certificatemodule/pages/signaturemodal.jsx

- issue for no signatures fetched resolved

signature modal issue resolved

---

server/src/modules/certificateModule/controllers/formDataToObject.js
server/src/modules/certificateModule/helper/multer.middleware.js

- updated file path to absolute in multer.middleware.js

updated file path

---

server/src/models/diabeticsModule/doctor.js
server/src/modules/diabeticsModule/controllers/doctor.js
server/src/modules/diabeticsModule/routes/doctor.js
server/src/modules/diabeticsModule/routes/patient.js

doctor and patient's middelewares

---

client/src/filedownload/pdfMakeInitializer.js
client/src/timetableadmin/masterfaculty.jsx
client/src/timetableadmin/masterroom.jsx
client/src/timetableadmin/mastersem.jsx
server/yarn.lock

marked required fields with star on mastersem, masterroom and masterfaculty pages

initial PR

---

client/src/timetableadmin/admin.jsx
client/src/timetableadmin/mastersearch.jsx
server/src/models/timetable.js
server/src/modules/timetableModule/controllers/timetableprofile.js
server/src/modules/timetableModule/routes/timetable.js

now admin can make a session current through admin page and it will be selected as default in mastersearch page

added default session functionality

---

client/package.json
client/src/App.jsx
client/src/diabeticsModule/components/DailyDosageForm.jsx
client/src/diabeticsModule/components/admin/AdminDashboard.jsx
client/src/diabeticsModule/components/admin/DoctorDetailView.jsx
client/src/diabeticsModule/components/admin/HospitalDetailView.jsx
client/src/diabeticsModule/components/doctor/DoctorDashboard.jsx
client/src/diabeticsModule/components/doctor/PatientDetailView.jsx
client/src/diabeticsModule/components/patient/PatientDashboard.jsx
client/src/diabeticsModule/components/patient/PatientHistory.jsx
client/src/diabeticsModule/pages/DoctorDetailView.jsx
client/src/diabeticsModule/pages/HospitalDetailView.jsx
client/yarn.lock
server/src/models/diabeticsModule/dailyDosage.js
server/src/modules/diabeticsModule/controllers/dailyDosage.js
server/src/modules/diabeticsModule/controllers/doctor.js
server/src/modules/diabeticsModule/controllers/hospital.js
server/src/modules/diabeticsModule/controllers/patient.js
server/src/modules/diabeticsModule/controllers/sickday.js
server/src/modules/diabeticsModule/routes/dailyDosage.js
server/src/modules/diabeticsModule/routes/doctor.js
server/src/modules/diabeticsModule/routes/hospital.js
server/src/modules/diabeticsModule/routes/patient.js

This PR implements core functionality for the diabetics module, addressing several issues: Fixes: - #1066: Add doctor and hospital detail view components - #1067: Implement admin dashboard and hospital management - #1070: Changes in daily dosage page - #1071: Patient dashboard page linking - #1072: Doctor dashboard backend linking - #1078: Patient linking to doctor dashboard - #1079: Save timestamp during daily entry Changes include: 1. New detail view components for doctors and hospitals 2. Improved daily dosage form with timestamp tracking 3. Doctor dashboard with patient linking functionality 4. Patient dashboard and history implementation 5. Admin dashboard with hospital management 6. Various minor fixes and dependency updates

fix: implement diabetics module core functionality

---

client/src/components/home/Navbar.jsx
client/src/diabeticsModule/components/DMNavbar.jsx
server/src/modules/diabeticsModule/controllers/doctor.js
server/src/modules/diabeticsModule/controllers/patient.js
server/src/modules/diabeticsModule/routes/doctor.js
server/src/modules/diabeticsModule/routes/patient.js

Implements doctor-patient assignment functionality and navigation improvements. Fixes #1065

Implement Doctor-Patient Assignment and Custom Navbar in Diabetics Module

---

client/src/App.jsx
client/src/diabeticsModule/components/DMNavbar.jsx
client/src/diabeticsModule/components/admin/DoctorDetailView.jsx
client/src/diabeticsModule/components/admin/HospitalDetailView.jsx
client/src/diabeticsModule/components/doctor/PatientDetailView.jsx
client/src/diabeticsModule/components/patient/PatientDashboard.jsx
client/src/diabeticsModule/components/patient/PatientHistory.jsx
client/src/diabeticsModule/pages/DoctorDetailView.jsx
client/src/diabeticsModule/pages/HospitalDetailView.jsx
client/src/diabeticsModule/pages/PatientDetailView.jsx
client/src/diabeticsModule/pages/PatientHistory.jsx

make the patient history accessible from the patient view; update patient history page to use the patient id from url instead of localStorage; remove history page link from the navbar; update detail views to use the params from the URL and add fallbacks; update patient details UI to include data graph of the patient and also organize the details better

Update the UI of Patient details view and add patient history table functionality for doctor and dm-admin roles

---

client/src/timetableadmin/commonslot.jsx
server/src/modules/timetableModule/controllers/timetableprofile.js
server/src/modules/timetableModule/routes/timetable.js

fixed the problem of faculty dropdown

fixed /tt/commonslot

---

client/src/timetableadmin/viewmasterclasstable.jsx

page was trying to render an object directly in jsx instead of string

fixed /tt/masterdata

---

client/src/timetableadmin/mastersearch.jsx

issues regarding faculty dropdown fixed

fixed /timetable

---

client/src/timetableadmin/admin.jsx

button will only show if there are time table mapped to the session else N/A will be displayed

added "Make current" button to session table in AdminPage

---

client/package.json
client/src/App.jsx
client/src/timetableadmin/admin.jsx
client/src/timetableadmin/creatett.jsx
client/src/timetableadmin/masterdelete.jsx
client/src/timetableadmin/viewMessages.jsx
client/src/timetableadmin/viewinstituteload.jsx
client/yarn.lock
server/src/index.js
server/src/models/message.js
server/src/modules/timetableModule/controllers/message.js
server/src/modules/timetableModule/routes/index.js
server/src/modules/timetableModule/routes/message.js

- Implemented message creation and retrieval in the timetable module.
- Added Message model and controller for handling messages.
- Integrated message routes with appropriate middleware for protection.
- Updated AdminPage and CreateTimetable components to support message sending and notifications.

Added messaging feature for timetable admin to coordinators

---

client/src/timetableadmin/departmentloadallocation.jsx
client/src/timetableadmin/viewinstituteloadmaster.jsx
server/src/modules/timetableModule/controllers/timetableprofile.js
server/src/modules/timetableModule/routes/timetable.js

fix: /tt/code/generatepdf/loadallocation, and /tt/masterload

---

client/src/App.jsx
client/src/filedownload/pdfMakeInitializer.js
client/src/timetableadmin/importt.jsx
client/src/timetableadmin/timetable.jsx
client/yarn.lock
server/src/modules/timetableModule/controllers/importdata.js
server/src/modules/timetableModule/routes/importdata.js

import option added. TT coordinators can import data of subject, sem, room directly from previous sem

import timetable updated

---

client/src/filedownload/downloadsummary.js
client/src/filedownload/mergepdfdocuments.jsx
client/src/timetableadmin/printSummary.jsx

Fix PDF generation and data fetching in summary and merge components

---

client/src/App.jsx
client/src/timetableadmin/admin.jsx
client/src/timetableadmin/creatett.jsx
client/src/timetableadmin/masterdelete.jsx
client/src/timetableadmin/messages.jsx
client/src/timetableadmin/viewMessages.jsx
server/src/modules/timetableModule/controllers/message.js

placed all the message functionality in one place. Added notifications alert to the dttc view message button

placed all the message functionality in one place. Added notifications alert to the dttc view message button

---

client/package.json
client/src/timetableadmin/mastersearch.jsx
client/yarn.lock
server/src/modules/timetableModule/controllers/facultyprofile.js
server/src/modules/timetableModule/routes/faculty.js

- Implemented a new method `getFacultyByName` in `facultyprofile.js` to search for faculty by name or department using a regex query.
- Added a new route `/search` in `faculty.js` to handle GET requests for faculty search, returning up to 10 matching results.
- Enhanced error handling for invalid queries and internal server errors.

feat: add faculty search functionality
